const movieCreditsResponse = {
  "id": 629374,
  "cast": [
    {
      "adult": false,
      "gender": 0,
      "id": 1336797,
      "known_for_department": "Acting",
      "name": "Mike Hanford",
      "original_name": "Mike Hanford",
      "popularity": 6.885,
      "profile_path": null,
      "cast_id": 2,
      "character": "John Lennon",
      "credit_id": "5d73d18c3a4a12356fd0dc81",
      "order": 0
    },
    {
      "adult": false,
      "gender": 1,
      "id": 1488952,
      "known_for_department": "Acting",
      "name": "Mary Holland",
      "original_name": "Mary Holland",
      "popularity": 23.84,
      "profile_path": "/iwEK2fIrU1q7aijjD8FI9hCUMEL.jpg",
      "cast_id": 3,
      "character": "Shelley",
      "credit_id": "5d73d198127778001128d141",
      "order": 1
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1261959,
      "known_for_department": "Production",
      "name": "Jace Armstrong",
      "original_name": "Jace Armstrong",
      "popularity": 6.705,
      "profile_path": null,
      "cast_id": 4,
      "character": "Waiter",
      "credit_id": "5d73d1ad127778730427b52b",
      "order": 2
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1254620,
      "known_for_department": "Acting",
      "name": "Michael Blaiklock",
      "original_name": "Michael Blaiklock",
      "popularity": 8.517,
      "profile_path": "/p8LskTqAbnop2904sPW952wU9GU.jpg",
      "cast_id": 5,
      "character": "Security Guad",
      "credit_id": "5d73d1b6209f180014fc80cf",
      "order": 3
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1696150,
      "known_for_department": "Acting",
      "name": "Ross Kimball",
      "original_name": "Ross Kimball",
      "popularity": 8.805,
      "profile_path": "/cyqbs3LfkjUxy9ciojAICFM9oDj.jpg",
      "cast_id": 6,
      "character": "Bully",
      "credit_id": "5d73d1bf209f186914fc6c8e",
      "order": 4
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1598900,
      "known_for_department": "Acting",
      "name": "Zeke Nicholson",
      "original_name": "Zeke Nicholson",
      "popularity": 6.722,
      "profile_path": null,
      "cast_id": 7,
      "character": "David",
      "credit_id": "5d73d1c7209f180013fc73fe",
      "order": 5
    }
  ],
  "crew": [
    {
      "adult": false,
      "gender": 0,
      "id": 1304300,
      "known_for_department": "Costume & Make-Up",
      "name": "Shelley Rucker",
      "original_name": "Shelley Rucker",
      "popularity": 1.025,
      "profile_path": null,
      "credit_id": "5d73d2a8209f180014fc81d5",
      "department": "Costume & Make-Up",
      "job": "Makeup & Hair"
    },
    {
      "adult": false,
      "gender": 0,
      "id": 2239633,
      "known_for_department": "Production",
      "name": "Carl Fieler",
      "original_name": "Carl Fieler",
      "popularity": 1.57,
      "profile_path": null,
      "credit_id": "5d73d252127778675f27ac34",
      "department": "Production",
      "job": "Producer"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1381407,
      "known_for_department": "Production",
      "name": "Jefferson Dutton",
      "original_name": "Jefferson Dutton",
      "popularity": 4.942,
      "profile_path": null,
      "credit_id": "5d73d297209f183b07fb1456",
      "department": "Editing",
      "job": "Editor"
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1619144,
      "known_for_department": "Costume & Make-Up",
      "name": "Monica Chamberlain",
      "original_name": "Monica Chamberlain",
      "popularity": 1.926,
      "profile_path": null,
      "credit_id": "5d73d2d9127778001128d269",
      "department": "Costume & Make-Up",
      "job": "Costumer"
    },
    {
      "adult": false,
      "gender": 0,
      "id": 2405829,
      "known_for_department": "Production",
      "name": "Brian Christopher",
      "original_name": "Brian Christopher",
      "popularity": 1.854,
      "profile_path": null,
      "credit_id": "5d73d304209f180014fc8226",
      "department": "Production",
      "job": "Production Assistant"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1381407,
      "known_for_department": "Production",
      "name": "Jefferson Dutton",
      "original_name": "Jefferson Dutton",
      "popularity": 4.942,
      "profile_path": null,
      "credit_id": "5d73d240127778730427b5a4",
      "department": "Production",
      "job": "Executive Producer"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1381407,
      "known_for_department": "Production",
      "name": "Jefferson Dutton",
      "original_name": "Jefferson Dutton",
      "popularity": 4.942,
      "profile_path": null,
      "credit_id": "5d73d1793a4a120012d244e1",
      "department": "Directing",
      "job": "Director"
    },
    {
      "adult": false,
      "gender": 0,
      "id": 2119044,
      "known_for_department": "Sound",
      "name": "Doug Beatty",
      "original_name": "Doug Beatty",
      "popularity": 0.913,
      "profile_path": null,
      "credit_id": "5d73d2b3127778001328d183",
      "department": "Sound",
      "job": "Sound Mixer"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1381410,
      "known_for_department": "Editing",
      "name": "Chris VanArtsdalen",
      "original_name": "Chris VanArtsdalen",
      "popularity": 3.749,
      "profile_path": "/1JMGkIzL3fK5j5wT4qk3FwAHtJv.jpg",
      "credit_id": "5d73d2c2209f183b07fb1487",
      "department": "Visual Effects",
      "job": "Digital Effects Producer"
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1336797,
      "known_for_department": "Acting",
      "name": "Mike Hanford",
      "original_name": "Mike Hanford",
      "popularity": 6.885,
      "profile_path": null,
      "credit_id": "5d73d2613a4a12356fd0dd2a",
      "department": "Production",
      "job": "Executive Producer"
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1490758,
      "known_for_department": "Directing",
      "name": "Robby Massey",
      "original_name": "Robby Massey",
      "popularity": 1.099,
      "profile_path": null,
      "credit_id": "5d73d2cf127778001528cfb8",
      "department": "Camera",
      "job": "Camera Operator"
    },
    {
      "adult": false,
      "gender": 1,
      "id": 1354983,
      "known_for_department": "Acting",
      "name": "Martha Cary",
      "original_name": "Martha Cary",
      "popularity": 1.438,
      "profile_path": null,
      "credit_id": "5d73d2e3209f183b07fb14a0",
      "department": "Directing",
      "job": "Script Supervisor"
    },
    {
      "adult": false,
      "gender": 1,
      "id": 2405830,
      "known_for_department": "Production",
      "name": "Amelia Marino",
      "original_name": "Amelia Marino",
      "popularity": 4.108,
      "profile_path": null,
      "credit_id": "5d73d30f209f180012fc754d",
      "department": "Production",
      "job": "Production Assistant"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 115825,
      "known_for_department": "Camera",
      "name": "Andy Knapp",
      "original_name": "Andy Knapp",
      "popularity": 1.286,
      "profile_path": null,
      "credit_id": "61aae34d4f3a4c001c8b3822",
      "department": "Camera",
      "job": "Director of Photography"
    }
  ]
};
