const trendingMoviesResponse = {
  "page": 1,
  "results": [
    {
      "backdrop_path": "/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
      "id": 823464,
      "original_title": "Godzilla x Kong: The New Empire",
      "overview":
          "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
      "poster_path": "/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Godzilla x Kong: The New Empire",
      "original_language": "en",
      "genre_ids": [878, 28, 12],
      "popularity": 3384.641,
      "release_date": "2024-03-27",
      "video": false,
      "vote_average": 6.992,
      "vote_count": 1405
    },
    {
      "backdrop_path": "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
      "id": 653346,
      "original_title": "Kingdom of the Planet of the Apes",
      "overview":
          "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
      "poster_path": "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Kingdom of the Planet of the Apes",
      "original_language": "en",
      "genre_ids": [878, 12, 28],
      "popularity": 2372.67,
      "release_date": "2024-05-08",
      "video": false,
      "vote_average": 7.306,
      "vote_count": 328
    },
    {
      "backdrop_path": "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
      "id": 693134,
      "original_title": "Dune: Part Two",
      "overview":
          "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
      "poster_path": "/gho58bYmw9juYXmUSHRJKOngJGn.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Dune: Part Two",
      "original_language": "en",
      "genre_ids": [878, 12],
      "popularity": 1105.259,
      "release_date": "2024-02-27",
      "video": false,
      "vote_average": 8.205,
      "vote_count": 3876
    },
    {
      "backdrop_path": "/k37Ccgu05Am1xxgN5GaW0HX9Kkl.jpg",
      "id": 1087388,
      "original_title": "Sting",
      "overview":
          "After raising an unnervingly talented spider in secret, 12-year-old Charlotte must face the truth about her pet and fight for her family's survival.",
      "poster_path": "/zuSAZIG1PSrxFwPeAlGtg9LTwxo.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Sting",
      "original_language": "en",
      "genre_ids": [27, 53],
      "popularity": 54.188,
      "release_date": "2024-04-12",
      "video": false,
      "vote_average": 7.278,
      "vote_count": 18
    },
    {
      "backdrop_path": "/5cCfqeUH2f5Gnu7Lh9xepY9TB6x.jpg",
      "id": 967847,
      "original_title": "Ghostbusters: Frozen Empire",
      "overview":
          "After the original team developed a top-secret research laboratory to take the shattered ghosts to the next level. But when the discovery of an ancient artifact unleashes an evil force, both new and old must join forces to protect their homeland and save the world from the Second Ice Age... from the very thing that unleashes an unstoppable force from the depths of history. As chaos reigns and pure evil plunges the world into darkness, the Ghostbusters must step forward once again to save humanity from the brink of doom. With two generations of Ghostbusters fighting side by side, the stakes have never been higher. Will they be able to avert the inevitable before everything freezes?",
      "poster_path": "/e1J2oNzSBdou01sUvriVuoYp0pJ.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Ghostbusters: Frozen Empire",
      "original_language": "en",
      "genre_ids": [14, 12, 35],
      "popularity": 1205.297,
      "release_date": "2024-03-20",
      "video": false,
      "vote_average": 6.734,
      "vote_count": 695
    },
    {
      "backdrop_path": "/s5znBQmprDJJ553IMQfwEVlfroH.jpg",
      "id": 799583,
      "original_title": "The Ministry of Ungentlemanly Warfare",
      "overview":
          "Taking place during World War II, the British Army assigns a group of competent soldiers to carry out a mission against the Nazi forces behind enemy lines... A true story about a secret British World War II organization; the Special Operations Executive. Founded by Winston Churchill, their irregular warfare against the Germans helped to change the course of the war, and gave birth to modern black operations.",
      "poster_path": "/x8Od47ZMDDT3ho3IRdXNmcjHknX.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "The Ministry of Ungentlemanly Warfare",
      "original_language": "en",
      "genre_ids": [28, 10752, 18],
      "popularity": 306.599,
      "release_date": "2024-04-18",
      "video": false,
      "vote_average": 7.301,
      "vote_count": 138
    },
    {
      "backdrop_path": "/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg",
      "id": 1111873,
      "original_title": "Abigail",
      "overview":
          "A group of criminals kidnaps a teenage ballet dancer, the daughter of a notorious gang leader, in order to obtain a ransom of \$50 million, but over time, they discover that she is not just an ordinary girl. After the kidnappers begin to diminish, one by one, they discover, to their increasing horror, that they are locked inside with an unusual girl.",
      "poster_path": "/7qxG0zyt29BI0IzFDfsps62kbQi.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Abigail",
      "original_language": "en",
      "genre_ids": [27, 53],
      "popularity": 1102.818,
      "release_date": "2024-04-18",
      "video": false,
      "vote_average": 6.946,
      "vote_count": 367
    },
    {
      "backdrop_path": "/jTWllMddJzCb7hBVNZICtgKhYM9.jpg",
      "id": 639720,
      "original_title": "IF",
      "overview":
          "A girl discovers she can see everyone's imaginary friends and embarks on a magical adventure to reconnect forgotten IFs with their kids.",
      "poster_path": "/xbKFv4KF3sVYuWKllLlwWDmuZP7.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "IF",
      "original_language": "en",
      "genre_ids": [35, 14, 10751],
      "popularity": 223.591,
      "release_date": "2024-05-08",
      "video": false,
      "vote_average": 7.607,
      "vote_count": 14
    },
    {
      "backdrop_path": "/zj13HSGkT7EIRwUKnXrurgkQ1qc.jpg",
      "id": 786892,
      "original_title": "Furiosa: A Mad Max Saga",
      "overview":
          "As the world falls, young Furiosa is snatched from the Green Place of Many Mothers into the hands of a great biker horde led by the warlord Dementus. Sweeping through the wasteland, they encounter the citadel presided over by Immortan Joe. The two tyrants wage war for dominance, and Furiosa must survive many trials as she puts together the means to find her way home.",
      "poster_path": "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Furiosa: A Mad Max Saga",
      "original_language": "en",
      "genre_ids": [878, 28, 12],
      "popularity": 292.919,
      "release_date": "2024-05-22",
      "video": false,
      "vote_average": 0,
      "vote_count": 0
    },
    {
      "backdrop_path": "/fY3lD0jM5AoHJMunjGWqJ0hRteI.jpg",
      "id": 940721,
      "original_title": "ゴジラ-1.0",
      "overview":
          "Postwar Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb.",
      "poster_path": "/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Godzilla Minus One",
      "original_language": "ja",
      "genre_ids": [878, 27, 28],
      "popularity": 1895.443,
      "release_date": "2023-11-03",
      "video": false,
      "vote_average": 7.668,
      "vote_count": 1016
    },
    {
      "backdrop_path": "/30wIzvX5LmiYtsjxDGt1NCqx6A.jpg",
      "id": 1015634,
      "original_title": "Sasquatch Sunset",
      "overview":
          "In the misty forests of North America, a family of Sasquatches—possibly the last of their enigmatic kind—embark on an absurdist, epic, hilarious, and ultimately poignant journey over the course of one year. These shaggy and noble giants fight for survival as they find themselves on a collision course with the ever-changing world around them.",
      "poster_path": "/s43rgDGRDOB12prgK9YfWPEIyAh.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Sasquatch Sunset",
      "original_language": "en",
      "genre_ids": [14, 35],
      "popularity": 21.496,
      "release_date": "2024-04-12",
      "video": false,
      "vote_average": 6,
      "vote_count": 8
    },
    {
      "backdrop_path": "/v5XyXZe8FADw8iHupB4L7QOAwH9.jpg",
      "id": 748783,
      "original_title": "The Garfield Movie",
      "overview":
          "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
      "poster_path": "/zK2sFxZcelHJRPVr242rxy5VK4T.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "The Garfield Movie",
      "original_language": "en",
      "genre_ids": [16, 35, 10751],
      "popularity": 629.045,
      "release_date": "2024-04-30",
      "video": false,
      "vote_average": 6.574,
      "vote_count": 61
    },
    {
      "backdrop_path": "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
      "id": 438631,
      "original_title": "Dune",
      "overview":
          "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
      "poster_path": "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Dune",
      "original_language": "en",
      "genre_ids": [878, 12],
      "popularity": 571.112,
      "release_date": "2021-09-15",
      "video": false,
      "vote_average": 7.779,
      "vote_count": 11602
    },
    {
      "backdrop_path": "/ieYXS9LZG5AEkkv4bdptvw99snj.jpg",
      "id": 402431,
      "original_title": "Wicked",
      "overview":
          "Elphaba, an ostracized but defiant girl born with green skin, and Glinda, a privileged aristocrat born popular, become extremely unlikely friends in the magical Land of Oz. As the two girls struggle with their opposing personalities, their friendship is tested as both begin to fulfill their destinies as Glinda the Good and The Wicked Witch of the West. The first of a two-part film adaptation of the Broadway musical.",
      "poster_path": "/aIbd4vaSc1ytOlFyon5kGDayDhg.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Wicked",
      "original_language": "en",
      "genre_ids": [18, 14, 10749],
      "popularity": 77.045,
      "release_date": "2024-11-27",
      "video": false,
      "vote_average": 0,
      "vote_count": 0
    },
    {
      "backdrop_path": "/m0XCtFisSD0O6P55G1pUHdFccuL.jpg",
      "id": 1093231,
      "original_title": "Mother of the Bride",
      "overview":
          "A doting mom jets off to a tropical island resort for her daughter's wedding — only to discover the groom's father is the ex she hasn't seen in decades.",
      "poster_path": "/vdTvwykMWvVgdaViBVRh8IFTku5.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Mother of the Bride",
      "original_language": "en",
      "genre_ids": [10749, 35],
      "popularity": 211.784,
      "release_date": "2024-05-08",
      "video": false,
      "vote_average": 5.973,
      "vote_count": 73
    },
    {
      "backdrop_path": "/662Qzyr5puD3MydSOFTCNVMBCnr.jpg",
      "id": 61791,
      "original_title": "Rise of the Planet of the Apes",
      "overview":
          "A highly intelligent chimpanzee named Caesar has been living a peaceful suburban life ever since he was born. But when he gets taken to a cruel primate facility, Caesar decides to revolt against those who have harmed him.",
      "poster_path": "/cjLsuP75UDlRdJVMXzXg3TJ4umX.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Rise of the Planet of the Apes",
      "original_language": "en",
      "genre_ids": [53, 28, 18, 878],
      "popularity": 529.346,
      "release_date": "2011-08-03",
      "video": false,
      "vote_average": 7.31,
      "vote_count": 11345
    },
    {
      "backdrop_path": "/4TFCA5Lm5miseV3Wy02yxurEQL9.jpg",
      "id": 119450,
      "original_title": "Dawn of the Planet of the Apes",
      "overview":
          "A group of scientists in San Francisco struggle to stay alive in the aftermath of a plague that is wiping out humanity, while Caesar tries to maintain dominance over his community of intelligent apes.",
      "poster_path": "/kScdQEwS9jPEdnO23XjGAtaoRcT.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Dawn of the Planet of the Apes",
      "original_language": "en",
      "genre_ids": [878, 28, 18, 53],
      "popularity": 810.022,
      "release_date": "2014-07-08",
      "video": false,
      "vote_average": 7.317,
      "vote_count": 10849
    },
    {
      "backdrop_path": "/lA6KdSkCTxwzvqzPqxch997RabQ.jpg",
      "id": 560016,
      "original_title": "Monkey Man",
      "overview":
          "Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.",
      "poster_path": "/4lhR4L2vzzjl68P1zJyCH755Oz4.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Monkey Man",
      "original_language": "en",
      "genre_ids": [28, 53],
      "popularity": 150.274,
      "release_date": "2024-04-03",
      "video": false,
      "vote_average": 7.227,
      "vote_count": 366
    },
    {
      "backdrop_path": "/nmXlpuXJhOv9yKJVhWPaLgpUChl.jpg",
      "id": 1148713,
      "original_title": "El correo",
      "overview":
          "After shrewdly seizing his chance to join a money-laundering scheme, a modest valet dives into a world of fast cash, fast cars — and an inevitable crash.",
      "poster_path": "/smiEA0WTErj1FlowpAuEGPJKyZp.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "The Courier",
      "original_language": "es",
      "genre_ids": [53, 80, 18],
      "popularity": 61.053,
      "release_date": "2024-01-19",
      "video": false,
      "vote_average": 6.2,
      "vote_count": 15
    },
    {
      "backdrop_path": "/72clA3Tlo9hGY815pubweHOxVAR.jpg",
      "id": 937287,
      "original_title": "Challengers",
      "overview":
          "Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a \"Challenger\" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi's former boyfriend.",
      "poster_path": "/H6vke7zGiuLsz4v4RPeReb9rsv.jpg",
      "media_type": "movie",
      "adult": false,
      "title": "Challengers",
      "original_language": "en",
      "genre_ids": [18, 10749],
      "popularity": 224.891,
      "release_date": "2024-04-18",
      "video": false,
      "vote_average": 7.426,
      "vote_count": 490
    }
  ],
  "total_pages": 1000,
  "total_results": 20000
};
