const searchResponse = {
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/sTrbHp9ERN8YlUsnbDPmXW8QPLq.jpg",
      "genre_ids": [35],
      "id": 629374,
      "original_language": "en",
      "original_title": "John",
      "overview":
          "A day in the life of John Lennon, alive and well in modern-day New York City. The former Beatle squabbles with a security guard, commiserates with his best friend over lunch, and upsets a bully.",
      "popularity": 9.782,
      "poster_path": "/jI3J69Yzl2NzeKnNBOTDf00jodx.jpg",
      "release_date": "2018-09-08",
      "title": "John",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 20
    },
    {
      "adult": false,
      "backdrop_path": "/f2OZIyRsbE3uJ1UMVnGVDcSNtNX.jpg",
      "genre_ids": [99],
      "id": 744234,
      "original_language": "en",
      "original_title": "John",
      "overview":
          "John tells the story of a young male, a psychiatric hospital patient who witnesses the death of another Black male patient at the hands of white staff. Blurring the boundaries between fact and fiction, this work draws from real life cases of mentally ill Black men who have died as a result of excessive force of the State.",
      "popularity": 5.199,
      "poster_path": null,
      "release_date": "2020-09-17",
      "title": "John",
      "video": false,
      "vote_average": 7.3,
      "vote_count": 13
    },
    {
      "adult": false,
      "backdrop_path": "/kKU7kWPnG4KfOpF7rtDEVk8xhmT.jpg",
      "genre_ids": [80, 53],
      "id": 1147514,
      "original_language": "ur",
      "original_title": "John",
      "overview":
          "A rollercoaster of emotions, where friendship and love collide with betrayal and heartbreak",
      "popularity": 2.828,
      "poster_path": "/b3kWvCoAL48qmhro9vgbC6Lb2PV.jpg",
      "release_date": "2023-07-14",
      "title": "John",
      "video": false,
      "vote_average": 6.2,
      "vote_count": 7
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [878, 18],
      "id": 553287,
      "original_language": "en",
      "original_title": "John",
      "overview":
          "We are in the year 2043 and our existence is immersed in a sea of apathy. A reflexion about our evolution as humans.",
      "popularity": 5.772,
      "poster_path": "/l9AMeqFMyp3wYWaHw90e1C65wDr.jpg",
      "release_date": "2017-09-01",
      "title": "John",
      "video": false,
      "vote_average": 7.9,
      "vote_count": 23
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [18],
      "id": 633533,
      "original_language": "en",
      "original_title": "John",
      "overview": "",
      "popularity": 4.229,
      "poster_path": null,
      "release_date": "1992-01-01",
      "title": "John",
      "video": false,
      "vote_average": 5.6,
      "vote_count": 4
    },
    {
      "adult": false,
      "backdrop_path": "/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
      "genre_ids": [28, 53, 80],
      "id": 603692,
      "original_language": "en",
      "original_title": "John Wick: Chapter 4",
      "overview":
          "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
      "popularity": 209.579,
      "poster_path": "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
      "release_date": "2023-03-22",
      "title": "John Wick: Chapter 4",
      "video": false,
      "vote_average": 7.739,
      "vote_count": 5917
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [],
      "id": 1194391,
      "original_language": "en",
      "original_title": "John",
      "overview":
          "John is an eighteen-year-old Latino male prostitute, living in the poorest area of Hollywood, L.A. He often steals condoms and medicine from the local stores to support himself, due to his inexperience in the hustling world. Peaches is a black trans prostitute, who often helps John financially. Miguel is an older hustler who teaches John how to please men. John often spends his night wandering through the street, looking for older men to buy him for the night. His clients, men who come from all levels of society, share with John their stories and secrets.",
      "popularity": 1.322,
      "poster_path": "/9dTxM3WEnEXz5CTJoqvfq8yHZyq.jpg",
      "release_date": "2023-10-02",
      "title": "John",
      "video": false,
      "vote_average": 7.8,
      "vote_count": 5
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [],
      "id": 1226925,
      "original_language": "en",
      "original_title": "John",
      "overview":
          "A bittersweet, touching, yet heartbreaking tale of two lost hearts meeting, by director and writer Oliver Lee and Bittersweetpictures.net. Powerful, moving, strong yet subtle. 'John' makes you not only think but feel.",
      "popularity": 1.762,
      "poster_path": "/olYBmvuT5c1J0yn9o98cbjn0iJO.jpg",
      "release_date": "2013-12-21",
      "title": "John",
      "video": false,
      "vote_average": 4.9,
      "vote_count": 9
    },
    {
      "adult": false,
      "backdrop_path": "/tHkujDqdPC9VQoFpEWU0QgWIZyM.jpg",
      "genre_ids": [28, 53, 80],
      "id": 324552,
      "original_language": "en",
      "original_title": "John Wick: Chapter 2",
      "overview":
          "John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.",
      "popularity": 109.037,
      "poster_path": "/hXWBc0ioZP3cN4zCu6SN3YHXZVO.jpg",
      "release_date": "2017-02-08",
      "title": "John Wick: Chapter 2",
      "video": false,
      "vote_average": 7.327,
      "vote_count": 12615
    },
    {
      "adult": false,
      "backdrop_path": "/jtZix01UdmEmrZoGYy96zKNhC0I.jpg",
      "genre_ids": [18, 36],
      "id": 920220,
      "original_language": "pl",
      "original_title": "Johnny",
      "overview":
          "After a court order sends him to work at a hospice, an ex-criminal strikes up a friendship with a compassionate priest who changes his life.",
      "popularity": 16.726,
      "poster_path": "/6UoWEfDbLm8q9VtrnLRp0ORzbNd.jpg",
      "release_date": "2022-09-23",
      "title": "Johnny",
      "video": false,
      "vote_average": 7.4,
      "vote_count": 73
    },
    {
      "adult": false,
      "backdrop_path": "/nZ0BF8X2dSb8XbI24aNQH6wNcTj.jpg",
      "genre_ids": [35, 80],
      "id": 38397,
      "original_language": "it",
      "original_title": "La leggenda di Al, John e Jack",
      "overview":
          "Hapless Depression-era gangsters Al, John and Jack discover their boss wants to get rid of them and come up with a plan to sell him to the FBI, but Al's short-term memory loss could be a problem...",
      "popularity": 9.68,
      "poster_path": "/t7Xb04P1uCUJ1LADWD5RfqWGyDu.jpg",
      "release_date": "2002-12-13",
      "title": "The Legend of Al, John and Jack",
      "video": false,
      "vote_average": 7.057,
      "vote_count": 1121
    },
    {
      "adult": false,
      "backdrop_path": "/ipyxbPJrLB1g9AfHq4xH5nLWmew.jpg",
      "genre_ids": [28, 53],
      "id": 245891,
      "original_language": "en",
      "original_title": "John Wick",
      "overview":
          "Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.",
      "popularity": 99.301,
      "poster_path": "/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
      "release_date": "2014-10-22",
      "title": "John Wick",
      "video": false,
      "vote_average": 7.43,
      "vote_count": 18651
    },
    {
      "adult": false,
      "backdrop_path": "/vVpEOvdxVBP2aV166j5Xlvb5Cdc.jpg",
      "genre_ids": [28, 53, 80],
      "id": 458156,
      "original_language": "en",
      "original_title": "John Wick: Chapter 3 - Parabellum",
      "overview":
          "Super-assassin John Wick returns with a \$14 million price tag on his head and an army of bounty-hunting killers on his trail. After killing a member of the shadowy international assassin’s guild, the High Table, John Wick is excommunicado, but the world’s most ruthless hit men and women await his every turn.",
      "popularity": 123.801,
      "poster_path": "/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg",
      "release_date": "2019-05-15",
      "title": "John Wick: Chapter 3 - Parabellum",
      "video": false,
      "vote_average": 7.443,
      "vote_count": 10236
    },
    {
      "adult": false,
      "backdrop_path": "/ubNevniKd5NYo60DqYIQ29T0uyB.jpg",
      "genre_ids": [28, 12, 878],
      "id": 49529,
      "original_language": "en",
      "original_title": "John Carter",
      "overview":
          "John Carter is a war-weary, former military captain who's inexplicably transported to the mysterious and exotic planet of Barsoom (Mars) and reluctantly becomes embroiled in an epic conflict. It's a world on the brink of collapse, and Carter rediscovers his humanity when he realizes the survival of Barsoom and its people rests in his hands.",
      "popularity": 83.555,
      "poster_path": "/lCxz1Yus07QCQQCb6I0Dr3Lmqpx.jpg",
      "release_date": "2012-03-07",
      "title": "John Carter",
      "video": false,
      "vote_average": 6.317,
      "vote_count": 5420
    },
    {
      "adult": false,
      "backdrop_path": "/l0Iob8HNYJw4zyDrUCYF0YBHUCO.jpg",
      "genre_ids": [35],
      "id": 49399,
      "original_language": "fr",
      "original_title": "Janis et John",
      "overview":
          "Insurance salesman tries to get money from his hippie cousin by fulfilling his dream: arraigning for John Lennon and Janis Joplin's \"second coming\".",
      "popularity": 7.065,
      "poster_path": "/rDqz4rAEAfOxdLmANkzJMgWn24A.jpg",
      "release_date": "2003-10-15",
      "title": "Janis and John",
      "video": false,
      "vote_average": 6.1,
      "vote_count": 29
    },
    {
      "adult": false,
      "backdrop_path": "/fXRFn5Xdd4Rycb9ZiAeytm2odIp.jpg",
      "genre_ids": [80],
      "id": 1001019,
      "original_language": "fr",
      "original_title": "Un homme en fuite",
      "overview":
          "Johnny, a local activist, is wanted by the police after a robbery gone wrong. Paul, his childhood friend, comes back home after 15 years to find him before the police. Investigator Anna Radoszewski is also on Johnny’s trail. Thus begins a search in which memo- ries and secrets resurface. In a social context that shakes the town, everybody is looking for Johnny, who soon becomes the symbol of a revolt.",
      "popularity": 7.793,
      "poster_path": "/49zjPWin3zxEG7oDHHpeY7LVnzJ.jpg",
      "release_date": "2024-05-08",
      "title": "Chasing Johnny",
      "video": false,
      "vote_average": 6,
      "vote_count": 2
    },
    {
      "adult": false,
      "backdrop_path": "/uAX6NW8kFFrGmc0nJTWL7ajymQf.jpg",
      "genre_ids": [80, 18],
      "id": 17358,
      "original_language": "pt",
      "original_title": "Meu Nome não é Johnny",
      "overview":
          "The true story of João Guilherme Estrella (\"Johnny\"), a young middle-class bon vivant who became a big-time cocaine dealer in Rio de Janeiro in the early 1990s.",
      "popularity": 11.767,
      "poster_path": "/mKDKutX0bCvg401k68U9Nt7EG0y.jpg",
      "release_date": "2008-01-04",
      "title": "My Name Ain't Johnny",
      "video": false,
      "vote_average": 7.134,
      "vote_count": 254
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [],
      "id": 1270360,
      "original_language": "es",
      "original_title": "¿Me amas, John?",
      "overview":
          "From the bowels of the Teatro Colón, the rehearsals and staging of the opera Einstein on the Beach are shown. Shot in the week leading up to opening night, the film captures the work of the artists, technicians and musicians who make this opera possible.",
      "popularity": 2.621,
      "poster_path": "/8uYBVXeygi7r8ACeGKXRxFaKLuY.jpg",
      "release_date": "2024-04-22",
      "title": "Do You Love Me, John?",
      "video": false,
      "vote_average": 0,
      "vote_count": 0
    },
    {
      "adult": false,
      "backdrop_path": "/sBB39VMtByFltGGGW2c5N6LOAvj.jpg",
      "genre_ids": [18, 53, 80],
      "id": 8470,
      "original_language": "en",
      "original_title": "John Q",
      "overview":
          "John Quincy Archibald is a father and husband whose son is diagnosed with an enlarged heart and then finds out he cannot receive a transplant because HMO insurance will not cover it. Therefore, he decides to take a hospital full of patients hostage until the hospital puts his son's name on the donor's list.",
      "popularity": 50.894,
      "poster_path": "/xEE91LvXiqgs7Hmdl44LCzHtFf6.jpg",
      "release_date": "2002-02-15",
      "title": "John Q",
      "video": false,
      "vote_average": 7.101,
      "vote_count": 2300
    },
    {
      "adult": false,
      "backdrop_path": "/6EddheqLHdOnSaXKDrr2EDGqJtX.jpg",
      "genre_ids": [27, 28, 878],
      "id": 747731,
      "original_language": "en",
      "original_title": "Johnny Z",
      "overview":
          "A half-human, half-zombie named Johnny pursues the malevolent corporation responsible for his creation. With the expert guidance of a seasoned martial arts master, he seeks justice and retribution.",
      "popularity": 26.87,
      "poster_path": "/ok4g3VN8CXlU9qov83vFz576Ufx.jpg",
      "release_date": "2023-03-26",
      "title": "Johnny Z",
      "video": false,
      "vote_average": 5.4,
      "vote_count": 19
    }
  ],
  "total_pages": 123,
  "total_results": 2456
};
